### PR TITLE
Add ability to import feeds from an OPML file

### PR DESCRIPTION
**Pull request by drguildo**
I added the ability to import feeds from an OPML file using listparser. Feel free to tweak and merge if you feel it's useful to you.

### CODE REVIEW

**Comment by m3nu** [comment]
This looks pretty trivial, but I can see some use cases. What about existing entries? Duplicate check?

**Comment by m3nu** [comment]
Thanks for the last change. How about checking for duplicates?

**Comment by drguildo** [comment]
Does this look okay?

**Comment by m3nu** [comment]
Splendid. Merged.

**Pull request merged**
